#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
